# Fechamento Janeiro 2025

In [ ]:
!python3 -m pip install --upgrade pip

In [1]:
import pandas as pd
# from ofxparse import OfxParser

## Fatura Inter

In [2]:
inter_01 = pd.read_csv('fatura-inter-2025-01.csv')
inter_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Data        50 non-null     object
 1   Lançamento  50 non-null     object
 2   Categoria   50 non-null     object
 3   Tipo        50 non-null     object
 4   Valor       50 non-null     object
dtypes: object(5)
memory usage: 2.1+ KB

### Convertendo o tipo da coluna de valores

In [ ]:
inter_01['Valor']

# Remover o "R$" e o espaço
inter_01['Valor'] = inter_01['Valor'].str.replace(r'R\$\s*', '', regex=True)

# Remover os pontos usados como separadores de milhares
inter_01['Valor'] = inter_01['Valor'].str.replace(r'\.', '', regex=True)

# Substituir a vírgula por ponto e converter para float
inter_01['Valor'] = inter_01['Valor'].str.replace(',', '.').astype(float)

In [13]:
categorias_inter_01 = inter_01.groupby('Categoria')['Valor'].sum()
categorias_inter_01

Categoria
BARES               77.00
COMPRAS            115.73
DROGARIA           171.08
ENTRETENIMENTO      79.89
INTER              141.60
LIVRARIAS           70.00
OUTROS            2385.01
PAGAMENTOS          11.90
PETSHOP             39.90
RESTAURANTES       617.60
SUPERMERCADO       533.01
TRANSPORTE         513.22
VIAGEM             204.49
Name: Valor, dtype: float64

## Fatura Nubank

In [ ]:
!pip install ofxparse

In [15]:
nubank_01 = pd.read_csv('fatura-nubank-2025-01.csv')
nubank_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    35 non-null     object
 1   title   35 non-null     object
 2   amount  35 non-null     float64
dtypes: float64(1), object(2)
memory usage: 968.0+ bytes

In [18]:
nubank_01.head()

         date                   title  amount
0  2025-01-11          Capital Bistro   31.90
1  2025-01-11  Brasilia Part Planejam    9.00
2  2025-01-11                  Subway   42.50
3  2025-01-09      Auto Posto Andrade   34.76
4  2025-01-08     Localiza Rac Mtzal0  195.78

In [17]:
nubank_01.tail()

          date                                title  amount
30  2024-12-13                Rodosnack sem Limites   30.80
31  2024-12-13        Atacadao 031 As - Parcela 2/2   49.24
32  2024-12-13  Iberia Lineas Aereas - Parcela 4/10  536.27
33  2024-12-13               Drogasil - Parcela 2/3  129.59
34  2024-12-13  Listo *Willian Carval - Parcela 2/2  127.50

In [19]:
# Repo: https://github.com/jseutter/ofxparse

# Abrir e ler o arquivo OFX
with open('fatura-nubank-2025-01.ofx', 'r') as arquivo:
    ofx = OfxParser.parse(arquivo)

# Extrair transações da primeira conta no arquivo
conta = ofx.accounts[0]
transacoes = conta.statement.transactions

# Transformar as transações em uma lista de dicionários
dados = [
    {
        "Data": trans.date,
        "Descrição": trans.memo,
        "Valor": trans.amount,
    }
    for trans in transacoes
]

# Criar o DataFrame
df = pd.DataFrame(dados)

df

NameError: name 'OfxParser' is not defined